### PR TITLE
Add Saithriftv2 rpc server 

### PR DESCRIPTION
**Pull request by msosyak**
TBD

relates to https://github.com/barefootnetworks/sonic-buildimage/pull/33

### CODE REVIEW

**Comment by ravi861** [comment]
Can we remove all the PERL code and templates? We should only have a patch with the generated RPC file and the frontend CPP file.

**Comment by msosyak** [comment]
> Can we remove all the PERL code and templates? We should only have a patch with the generated RPC file and the frontend CPP file.

Yes, I have removed it. But what is the idea? I thought it is like a feature of a new RPC server.

**Comment by ravi861** [comment]
> > Can we remove all the PERL code and templates? We should only have a patch with the generated RPC file and the frontend CPP file.
> 
> Yes, I have removed it. But what is the idea? I thought it is like a feature of a new RPC server.

We will eventually have to come up with how to regenerate these RPC servers everytime something changes in SAI. For now, we can just checkin the generated source for MSFT.

**Comment by msosyak** [comment]
Closed in favor of https://github.com/opencomputeproject/SAI/pull/1388

**Pull request closed without merging**
