### PR TITLE
GOINGTOSAI: SWI-4544 - Prepare saiqueue.py file for upstreaming

### PR DESCRIPTION
**Pull request by mmysle**

### CODE REVIEW

**Comment by mmysle** [comment]
The HW-specific tests were removed, because it is impossible to create hierarchical structure; parent scheduler node cannot be added, because the operation is unsupported. There is no traffic generator to obtain significant load, cannot create congestion - it is the testing infrastructure limitation.

**Review by aljer — APPROVED** [review]
I have no comments, lgtm

**Review by ravi861 — APPROVED** [review]
Good to go

**Comment by mmysle** [comment]
SAI PTF queue module was uploaded for external review:
https://github.com/opencomputeproject/SAI/pull/1358

**Pull request closed without merging**
